import { useState } from 'react';
import './DecisionPage.css'
import { useNavigate } from 'react-router-dom';
import { useLocation } from "react-router-dom";

function DecisionPage() {
	const navigate = useNavigate();
    const location = useLocation();
    const { gamePassed } = location.state || {};
    const [choice, setChoice] = useState("");
    // let imgPathName;

    // function SetProperImg (){
    //     let pathName;
    //     if (gamePassed == true){
    //         pathName = "/game/GameImages/PassedLevel.png";
    //     } else {
    //         pathName = "/game/GameImages/FailedLevel.png";
    //     }
    //     return pathName;
    // }

    // imgPathName = SetProperImg();



    return (
    //Reference used for background colour: https://www.w3schools.com/cssref/pr_background-color.php
    <div style={{ backgroundColor: '#B1E0EE' }}>
      {/* First section of the Home page */}
      <div className="container mt-5">
        <div className="mb-5">
          {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#c473ca', border: '10px solid #215689' }}> */}
            <div>
              {/* Image generated by Copilot */}
              {/* <SetProperImg /> */}
              <img src="/game/GameImages/GameLogo.png" className="float-start me-3 rounded" style={{ width: "140px" }} alt="logo" />
              {/* Reference for textShadow: https://www.w3schools.com/cssref/css3_pr_text-shadow.php */}
              <div style={{ backgroundColor: '#4FE5F5'}}><br/><h1 style={{ color: '#1B0C7A', textShadow: '2px 5px 8px #c36ed6', align: 'center'}}>NumImajez</h1><br/></div>
            </div>  
            {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#f2cdda' }}>
              <p>We will have content coming soon!</p>
            </div> */}
          </div>
        {/* </div> */}
      </div> 

        {/* Display the proper image to the user
      <div className="container mt-5 d-flex justify-content-center align-items-center">
        <div style={{ display: "flex", gap: "2px"}}>
          <div className="d-flex justify-content-center align-items-center" style={{ backgroundColor: '#BEC7EE', width: "700px", height: "700px"}}><br/>
            <div style={{ backgroundColor: '#DBEDED', width: "550px", height: "500px"}}><br/>  
                {/* Add the parameter to say "pass" or "failed" */}
              {/* <img src={imgPathName} className="float-start me-3 rounded" style={{ width: "400px" }} alt="logo" />
            </div>
            <div style={{ backgroundColor: '#DBEDED', width: "550px", height: "500px"}}><br/>   
                <br /><br/><br/><button className="btn btn-primary d-flex justify-content-center align-items-center" onClick={() => navigate('/memory-game/results', { replace: true })}>Submit</button>
            </div>
          </div>
        </div>
      </div> */}

        {/* Display text to the user */}
      <div className="container mt-5 d-flex justify-content-center align-items-center">
        <div style={{ display: "flex", gap: "2px"}}>
          <div className="d-flex justify-content-center align-items-center" style={{ backgroundColor: '#BEC7EE', width: "700px", height: "700px"}}><br/>
            <div className = "d-flex flex-column justify-content-center align-items-center text-center" style={{ backgroundColor: '#DBEDED', width: "550px", height: "500px"}}><br/>  
                {/* Add the parameter to say "pass" or "failed" */}
                <p className = "d-flex justify-content-center align-items-center" style={{ color: '#000000', fontSize: "20px", fontWeight: 700, textAlign: 'center'}}>Do you want to try again?<br/><br /></p>
            {/* </div> */}
            {/* <div className = "d-flex flex-column justify-content-center align-items-center text-center" style={{ backgroundColor: '#DBEDED', width: "550px", height: "500px"}}><br/>  */}
                <br/><br/><p>Make your choice here!</p>
                {/* '/memory-game/results' or '/memory-game/'*/}
                <select id="choice" style={{ textAlign: 'center', width: '300px' }} value={choice} onChange={(e) => setChoice(e.target.value)}>
                    <option value="">Select</option>
                    <option value="/memory-game/">YES</option>
                    <option value="/memory-game/results">NO!</option>
                </select>
                <br /><br/><br/><button className="btn btn-primary d-flex justify-content-center align-items-center" onClick={() => navigate(`${choice}`, { replace: true, state: {gamePassed}})}>Submit</button>
            </div>
          </div>
        </div>
      </div>


        {/* Third section of the Home page, the footer */}
        <div className="container mt-5">
            <div className="mb-5">
                <div>
                {/* See if you can adjust the width to fit the screen */}
                <div style={{ backgroundColor: '#6FD5F4', width: "950px"}}><br/>
                    <p style={{ color: '#000000', fontSize: "20px", fontWeight: 700 }}>Designed by: Krystan Kornafel, a third year Software Engineering student.<br/><br /></p>
                </div>
                </div>  
            </div>
        </div>

    </div>

	);
}

export default DecisionPage;
