// import { set } from 'react-datepicker/dist/dist/date_utils.js';
import './ResultsPage.css'
import { useLocation } from "react-router-dom";
import { useNavigate } from 'react-router-dom';
// This image will be used to determine which image to display (Is it the "Yay! you won!" image, or display "you failed" image?)
// function DecideImageDisplay (){
//     return (

//     );
// }


function ResultsPage() {
    const navigate = useNavigate();
    const location = useLocation();
    const { gamePassed } = location.state || {};

    //Set the text for display
    let displayText;
    function SetText(){
        if (gamePassed == true){
            return "Congrats!\n You won!";
        } else {
            return "LEVEL FAILED :( \nBetter luck next time! ";
        }
    }

    displayText = SetText();

    //Set the image for display
    let imgPathName;
    function SetProperImg (){
        let pathName;
        if (gamePassed == true){
            pathName = "/game/GameImages/PassedLevel.png";
        } else {
            pathName = "/game/GameImages/FailedLevel.png";
        }
        return pathName;
    }

    imgPathName = SetProperImg();

	return (
    //Reference used for background colour: https://www.w3schools.com/cssref/pr_background-color.php
    <div style={{ backgroundColor: '#B1E0EE' }}>
      {/* First section of the Home page */}
      <div className="container mt-5">
        <div className="mb-5">
          {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#c473ca', border: '10px solid #215689' }}> */}
            <div>
              {/* Image generated by Copilot */}
              <img src="/game/GameImages/GameLogo.png" className="float-start me-3 rounded" style={{ width: "140px" }} alt="logo" />
              {/* Reference for textShadow: https://www.w3schools.com/cssref/css3_pr_text-shadow.php */}
              <div style={{ backgroundColor: '#4FE5F5'}}><br/><h1 style={{ color: '#1B0C7A', textShadow: '2px 5px 8px #c36ed6', align: 'center'}}>NumImajez</h1><br/></div>
            </div>  
            {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#f2cdda' }}>
              <p>We will have content coming soon!</p>
            </div> */}
          </div>
        {/* </div> */}
      </div> 

      {/* Display the text to the user */}
      <div className="container mt-5 d-flex justify-content-center align-items-center">
        <div style={{ display: "flex", gap: "2px"}}>
          <div className="d-flex justify-content-center align-items-center" style={{ backgroundColor: '#BEC7EE', width: "700px", height: "800px"}}><br/>
              <div style={{ backgroundColor: '#DBEDED', width: "550px", height: "700px"}}><br/>
                    <h1 style={{ color: '#000000'}}>{displayText}<br /></h1>
              
                <div><br/>  
                    {/* Add the parameter to say "pass" or "failed" */}
                    <img src={imgPathName} className="me-3 rounded" style={{ width: "400px" }} alt="logo" /> <br/>
                </div>
                <div><br/>  
                    {/* Prompt the user to go to the main page */}
                    {/* <br /><br/><br/><button className="btn btn-primary d-flex justify-content-center align-items-center" onClick={() => navigate('/memory-game/results', { pass in the level, contrast, and category from this round if the user asks to try again)}>Submit</button> */}
                    <br/><p style={{ color: '#181a59', textShadow: '2px 5px 8px #c36ed6', align: 'center'}}>Return to the main page to try another game!</p>
                    <br/><button className="btn btn-primary justify-content-center align-items-center" style={{width: "100px"}} onClick={() => navigate('/memory-game/')}>OK</button>
                </div>
              </div>
          </div>
        </div>
      </div>

        {/* Third section of the Home page, the footer */}
        <div className="container mt-5">
            <div className="mb-5">
                <div>
                {/* See if you can adjust the width to fit the screen */}
                <div style={{ backgroundColor: '#6FD5F4', width: "950px"}}><br/>
                    <p style={{ color: '#000000', fontSize: "20px", fontWeight: 700 }}>Designed by: Krystan Kornafel, a third year Software Engineering student.<br/><br /></p>
                </div>
                </div>  
            </div>
        </div>

    </div>

	);
}

export default ResultsPage
