// Collect the contact info from the user. Like with the payment page, no data will actually be stored.
// The goal is just to create a UI design for this. It is not centered around working with a database
// to store the data.
import './ContactInfoPg.css'
import { useNavigate } from 'react-router-dom';

function ContactInfoPage() {
  const navigate = useNavigate();
  return (
    <>
    {/* <div className="d-flex gap-2 mt-3">
        <Link to="/eCommerceStore/transactionComplete" className="btn btn-primary" style={{ marginLeft: 'auto' }}>
            Continue to Complete Transaction
        </Link>
      </div> */}
    {/* //Reference used for background colour: https://www.w3schools.com/cssref/pr_background-color.php */}
    <div style={{ backgroundColor: '#e6ce44' }}>
      {/* First section of the About page */}
      <div className="container mt-5">
        <div className="mb-5">
          {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#c473ca', border: '10px solid #215689' }}> */}
            <div>
              {/* Image generated by Copilot */}
              <br/><div className="border rounded p-3 mb-4" style={{ backgroundColor: '#e2e888', border: '10px solid #215689' }}><br/><h1>Enter your contact info:</h1></div>
              {/* Put the form here. Prompt for name, email, phone number and address */}
            
            </div>  
            {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#f2cdda' }}>
              <p>We will have content coming soon!</p>
            </div> */}
          </div>
        {/* </div> */}
      </div> 

      {/* Third section of the page: the footer */}
      <div className="container mt-5">
        <div className="mb-5">
            <div>
              <div style={{ backgroundColor: '#e6ce44'}}>
                <form>
                  {/* Reference for styling: https://www.pluralsight.com/resources/blog/guides/react-inline-styling */}
                  <br/><p style={{ color: '#000000', fontSize: "20px", fontWeight: 700, textAlign: "left" }}>Name:</p><br/>
                  <div class="input-group">
                    {/* IF you have time, adjust colour of boxes to: #D9D9D9 */}
                    <br/><input id="name" type="text" class="form-control" name="name" placeholder="First Last"/>
                  </div>
                  <br/><p style={{ color: '#000000', fontSize: "20px", fontWeight: 700, textAlign: "left" }}>Phone Number:</p><br/>
                  <div class="input-group">
                    <br/><input id="phone" type="text" class="form-control" name="phone" placeholder="(613)-123-4567"/>
                  </div>
                  <br/><p style={{ color: '#000000', fontSize: "20px", fontWeight: 700, textAlign: "left" }}>Email:</p><br/>
                  <div class="input-group">
                    <br/><input id="email" type="email" class="form-control" name="email" placeholder="someone@example.com"/>
                  </div>
                  <br/><p style={{ color: '#000000', fontSize: "20px", fontWeight: 700, textAlign: "left" }}>Address:</p><br/>
                  <div class="input-group">
                    <br/><input id="address" type="text" class="form-control" name="address" placeholder="Address"/>
                  </div>
                </form>
                <br/><button className="btn btn-primary" onClick={() => navigate('/eCommerceStore/transactionComplete', { replace: true })}>Submit</button>
              </div>
            </div>  
          </div>
      </div>

      {/* Third section of the Home page, the footer */}
      <div className="mt-5" style={{ width: '100vw', height: '100px', marginLeft: 'calc(50% - 50vw)', backgroundColor: '#F46FF0' }}>
        <br/><p style={{ color: '#000000', fontSize: '20px', fontWeight: 700, margin: 0, padding: '1rem 1.5rem' }}>
          Designed by: Krystan Kornafel, a third year Software Engineering student.
        </p>
      </div>
    </div>
  </>
  );
}

export default ContactInfoPage;