// Prompt user for hypothetical payment data. Since this is a prototype and not an actual design, 
// no data will be stored or processed. It just lets the user type in the information to show the 
// UI design. The goal is to create a visual design for how a payment page would look like in an
// e-commerce website.
import './PaymentPg.css'
// import {Link } from 'react-router-dom';
import { useNavigate } from 'react-router-dom';

//======================== Transaction Complete Page ====================================================================================
// Name: Krystan Kornafel
// Assignment: SEG3125 Assignment 4
// Description: This page allows the user to enter their payment info. This info is not being stored anywhere, and is strictly for demo purposes.
// After collecting the payment info, redirect user to the contactInfo page. 

function PaymentPg() {
  const navigate = useNavigate();
  return (
    <>
    {/* <div className="d-flex gap-2 mt-3">
        <Link to="/eCommerceStore/contactInfo" className="btn btn-primary" style={{ marginLeft: 'auto' }}>
            Continue to Contact Info
        </Link>
      </div> */}
                
     {/* //Reference used for background colour: https://www.w3schools.com/cssref/pr_background-color.php */}
    <div style={{ backgroundColor: '#e6ce44' }}>
      {/* First section of the About page */}
      <div className="container mt-5">
        <div className="mb-5">
          {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#c473ca', border: '10px solid #215689' }}> */}
            <div>
              {/* Image generated by Copilot */}
              <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#e2e888', border: '10px solid #215689' }}><br/><h1>Enter Your Payment Information</h1></div>
              {/* Put the form here. Prompt for card number, expiry date, cvv */}
               <form>
                  {/* Reference for styling: https://www.pluralsight.com/resources/blog/guides/react-inline-styling */}
                  <br/><p style={{ color: '#000000', fontSize: "20px", fontWeight: 700, textAlign: "left" }}>Card Number:</p><br/>
                  <div class="input-group">
                    {/* IF you have time, adjust colour of boxes to: #D9D9D9 */}
                    <br/><input id="name" type="text" class="form-control" name="cardNum" placeholder="1234 5678 9012 3456"/>
                  </div>
                  <br/><p style={{ color: '#000000', fontSize: "20px", fontWeight: 700, textAlign: "left" }}>Expiry Date:</p><br/>
                  <div class="input-group">
                    <br/><input id="expiry" type="text" class="form-control" name="expiry" placeholder="MM/YY"/>
                  </div>
                  <br/><p style={{ color: '#000000', fontSize: "20px", fontWeight: 700, textAlign: "left" }}>CVV:</p><br/>
                  <div class="input-group">
                    <br/><input id="cvv" type="text" class="form-control" name="cvv" placeholder="123"/>
                  </div>
                  <br/><p style={{ color: '#000000', fontSize: "20px", fontWeight: 700, textAlign: "left" }}>Mailing Address:</p><br/>
                  <div class="input-group">
                    <br/><input id="address" type="text" class="form-control" name="address" placeholder="Address"/>
                  </div>
                </form>
                <br/><button className="btn btn-primary" onClick={() => navigate('/eCommerceStore/contactInfo', { replace: true })}>Submit</button>
            </div>  
            {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#f2cdda' }}>
              <p>We will have content coming soon!</p>
            </div> */}
          </div>
        {/* </div> */}
      </div> 

      {/* Second section of the About page */}
       {/* Reference for center alignment: https://mdbootstrap.com/docs/react/layout/vertical-alignment/ */}
      <div className="container mt-5 d-flex justify-content-center align-items-center">
        <div className="mb-5">
          <div style={{ display: "flex", alignItems: "center", gap: "2px" }}>
          </div>
        </div>
      </div>

      

      {/* Third section of the page: the footer */}
      {/* Third section of the Home page, the footer */}
    <div className="mt-5" style={{ width: '100vw', height: '100px', marginLeft: 'calc(50% - 50vw)', backgroundColor: '#F46FF0' }}>
      <br/><p style={{ color: '#000000', fontSize: '20px', fontWeight: 700, margin: 0, padding: '1rem 1.5rem' }}>
        Designed by: Krystan Kornafel, a third year Software Engineering student.
      </p>
    </div>

    </div>
  </>
  );
}

export default PaymentPg;
