import {useNavigate} from 'react-router-dom';


function Survey() {
  const navigate = useNavigate();
  return (
    <>
    {/* <div className="d-flex gap-2 mt-3">
        <Link to="/eCommerceStore/contactInfo" className="btn btn-primary" style={{ marginLeft: 'auto' }}>
            Continue to Contact Info
        </Link>
      </div> */}
                
     {/* //Reference used for background colour: https://www.w3schools.com/cssref/pr_background-color.php */}
    <div style={{ backgroundColor: '#e6ce44' }}>
      {/* First section of the About page */}
      <div className="container mt-5">
        <div className="mb-5">
          {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#c473ca', border: '10px solid #215689' }}> */}
            <div>
              {/* Image generated by Copilot */}
              <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#e2e888', border: '10px solid #215689' }}><br/><h1>Enter Your Payment Information</h1></div>
              {/* Put the form here. Prompt for card number, expiry date, cvv */}
               <form>
                  {/* Reference for styling: https://www.pluralsight.com/resources/blog/guides/react-inline-styling */}
                  <br/><p style={{ color: '#000000', fontSize: "20px", fontWeight: 700, textAlign: "left" }}>How likely are you to recommend this website to a friend? :)</p><br/>
                  <div class="input-group">
                    {/* IF you have time, adjust colour of boxes to: #D9D9D9 */}
                    <select style={{ textAlign: 'left', width: '300px' }}>
                      <option value="doNothing">Select</option>
                      <option value="lovedIt">Love the site!</option>
                      <option value="ItIsOk">It is okay</option>
                      <option value="CouldBeBetter">Could be better :/</option>
                      <option value="NotLikely">Not likely :(</option>
                    </select>                  
                  </div>
                  
                </form>
                <br/><button className="btn btn-primary" onClick={() => navigate('/eCommerceStore', { replace: true })}>Submit</button>
            </div>  
            {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#f2cdda' }}>
              <p>We will have content coming soon!</p>
            </div> */}
          </div>
        {/* </div> */}
      </div> 

      {/* Second section of the About page */}
       {/* Reference for center alignment: https://mdbootstrap.com/docs/react/layout/vertical-alignment/ */}
      <div className="container mt-5 d-flex justify-content-center align-items-center">
        <div className="mb-5">
          <div style={{ display: "flex", alignItems: "center", gap: "2px" }}>
          </div>
        </div>
      </div>

      

      {/* Third section of the page: the footer */}
      {/* Third section of the Home page, the footer */}
    <div className="mt-5" style={{ width: '100vw', height: '100px', marginLeft: 'calc(50% - 50vw)', backgroundColor: '#F46FF0' }}>
      <br/><p style={{ color: '#000000', fontSize: '20px', fontWeight: 700, margin: 0, padding: '1rem 1.5rem' }}>
        Designed by: Krystan Kornafel, a third year Software Engineering student.
      </p>
    </div>

    </div>
  </>
  );
}

export default Survey;
