//import ReactDOM from 'react-dom/client';
import './Hairdresser.css'
import { Link, Outlet } from 'react-router-dom';
//import the sub-pages
import About from './services/About';
import ApplyNow from './services/ApplyNow';
import BookAppointment from './services/BookAppointment';
import ContactUs from './services/ContactUs';
//Final results after each form submitted
// import FinalPgApply from './services/FinalPgApply';
// import FinalPgAppointment from './services/FinalPgAppointment';
 import ServicesPage from './services/ServicesPage';
 import FinalPgApply from './services/FinalPgApply';
 import FinalPgAppointment from './services/FinalPgAppointment';
//import { Link } from "react-router-dom";


//======================== Main Page for the Service Site -> Hair Salon ===================================================
// Name: Krystan Kornafel
// Assignment: SEG3125 Assignment 2
// Description: This is the main React page for the Hair Salon service site that will be used to display all the required information. There are several sub-pages, including the About page with information about the company owner,
//the Apply Now page which contains a form to allow users to apply for a job at the salon, the Book Appointment page that allows you
//to select a service and a date for an appointment, a page with contact details, and lastly a page with a list of all the services that will be provided to the customers.



function Home()  {
  return (
    //Reference used for background colour: https://www.w3schools.com/cssref/pr_background-color.php
    <div style={{ backgroundColor: '#c473ca' }}>
      {/* First section of the Home page */}
      <div className="container mt-5">
        <div className="mb-5">
          {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#c473ca', border: '10px solid #215689' }}> */}
            <div>
              {/* Image generated by Copilot */}
              <img src="/Logo.png" className="float-start me-3 rounded" style={{ width: "175px" }} alt="logo" />
              <div style={{ backgroundColor: '#4FE5F5'}}><br/><h1>Chique Hairstylez</h1><br/></div>
            </div>  
            {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#f2cdda' }}>
              <p>We will have content coming soon!</p>
            </div> */}
          </div>
        {/* </div> */}
      </div> 

      {/* Second section of the Home page */}
      <div className="container mt-5">
        {/* Reference for center alignment: https://mdbootstrap.com/docs/react/layout/vertical-alignment/ */}
        <div className="mb-5 d-flex justify-content-center align-items-center">
          <div style={{ display: "flex", alignItems: "center", gap: "2px" }}>
            {/* Image generated by Copilot */}
            <img src="/Main_Pg_Backgrnd.png" className="float-left ms-3 rounded" style={{ width: "300px" }} alt="logo" />
            <div style={{ backgroundColor: '#4FE5F5', width: "400px", height: "300px"}}><br/>
              {/* Reference for styling: https://www.pluralsight.com/resources/blog/guides/react-inline-styling */}
              <p style={{ color: '#8F0CB0', fontSize: "20px", fontWeight: 700 }}><br/>Chique Hairstylez is a family owned hair salon. <br/><br/> Check out our services to see what we have to offer you!</p><br/>
            </div>
          </div>
        </div>
      </div>

      {/* Third section of the Home page */}
      <div className="container mt-5 d-flex justify-content-center align-items-center">
        <div style={{ display: "flex", gap: "2px"}}>
          <div>
            {/* Image generated by Copilot */}
            <Link to="/hairdresser/ServicesPage"><img src="/Services2_Img.png" className="float-left ms-3 rounded" style={{ width: "300px", height:"300px" }} alt="logo" /></Link>
            {/* <img src="/Services2_Img.png" className="float-left ms-3 rounded" style={{ width: "300px", height:"300px" }} alt="logo" /> */}
          </div>
          <div style={{ backgroundColor: '#4FE5F5', width: "400px", height: "300px"}}><br/>
              <p style={{ color: '#8F0CB0', fontSize: "20px", fontWeight: 700}}><br/>Contact Us<br/><br/>(613)-890-1234<br/>ChiqueHairstylez@gmail.com<br/><br/></p>
          </div>
        </div>
      </div>

      {/* Third section of the Home page, the footer */}
      <div className="container mt-5">
        <div className="mb-5">
            <div>
              <div style={{ backgroundColor: '#F46FF0'}}><br/>
                <p style={{ color: '#000000', fontSize: "20px", fontWeight: 700 }}><br/>Designed by: Krystan Kornafel, a third year Software Engineering student.<br/></p>
                <p style={{ color: '#690AE4', fontSize: "20px", fontWeight: 700 }}><br/>(613)-890-1234, ChiqueHairstylez@gmail.com<br/></p><br/><br/>
              </div>
            </div>  
          </div>
      </div>

    </div>

  );
}



function Navbar() {
  return (
    //Reference used for this: https://www.sitepoint.com/creating-a-navbar-in-react/
    //<nav className="navbar navbar-expand-lg navbar-dark bg-dark px-4">
    // <div className="navbar-center">
    <div className="container-fluid"style={{ backgroundColor: "#F46FF0", border: "1px solid #334155" }}> 
      <div className="navbar">
        {/* Reference used for spacing (aka "me-3, me-auto"): https://mdbootstrap.com/docs/react/utilities/spacing/ */}
        <ul className="navbar-nav me-auto mb-2 mb-lg-0 d-flex flex-row">
        {/* <div className="container-fluid"> */}
          {/* <span className="navbar-brand">Assign2</span> */}
          {/* <div className="navbar-nav"> */}
          {/* Add a link to the main UI page for the Portfolio */}
            <li className="nav-item me-3"><Link className="nav-link" to="/hairdresser">Home</Link></li>
            {/* <Link className="nav-link text-white" to="/about">About</Link> */}
            <li className="nav-item me-3"><Link className="nav-link" to="/hairdresser/about">About Us</Link></li>
            <li className="nav-item me-3"><Link className="nav-link" to="/hairdresser/applyNow">We are Hiring!</Link></li>
            <li className="nav-item me-3"><Link className="nav-link" to="/hairdresser/bookAppointment">Book Appointment</Link></li>
            <li className="nav-item"><Link className="nav-link" to="/hairdresser/contactUs">Contact Us</Link></li>
          {/* </div> */}
        {/* </div> */}
        </ul>
      </div>
    </div>
  );
}





function Hairdresser() {
  return (
    <>
      <Navbar />
      <Outlet />
    </>
  );
}

export default Hairdresser;

export { Home, About, ServicesPage, ApplyNow, FinalPgApply, BookAppointment, FinalPgAppointment, ContactUs };
