import './MemoryGame.css'
import { useNavigate } from 'react-router-dom';
import { Outlet } from 'react-router-dom';
import { useState } from "react";
//import the sub-pages
import GameStartPage from './game/GameStartPage';
import DecisionPage from './game/DecisionPage';
import ResultsPage from './game/ResultsPage';

//======================== Memory Game Page ====================================================================================
// Name: Krystan Kornafel
// Assignment: SEG3125 Assignment 3
// Description: This will be used as the main UI for the memory game site. It will call on subpages such as the GamePage.jsx, DecisionPage.jsx,
// and the ResultsPage.jsx, which display all the required components of each step in the game. Steps include: Select your level, category and 
// contrast type (done from the home page here), then go to the GameStartPage where the actualy images will be displayed and the timer will start.
// Next, once the user makes their selection(s) and hits submit to finalize the page, the user will then be redirected to the DecisionPage where 
// they can decided to continue or not. Once they are done playing the game, they will be directed to the final page UI, which will tell them if 
// if they passed the level or not. It will only look at the current results for the last session of the game to determine if the user passed.
// That means that if the user failed the level the first time, when they redo it the second time, it should only keep their latest score. 


function GameHome() {
   const navigate = useNavigate();
   //For the user's selections in the drop-down menu
    //  const userSelection = { level: 'EASY', contrast: 'LOW', category: 'BOATS'};
    const [level, setLevel] = useState("");
    const [contrast, setContrast] = useState("");
    const [category, setCategory] = useState("");

    return (
    //Reference used for background colour: https://www.w3schools.com/cssref/pr_background-color.php
    <div style={{ backgroundColor: '#B1E0EE' }}>
      {/* First section of the Home page */}
      <div className="container mt-5">
        <div className="mb-5">
          {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#c473ca', border: '10px solid #215689' }}> */}
            <div>
              {/* Image generated by Copilot */}
              <img src="/game/GameImages/GameLogo.png" className="float-start me-3 rounded" style={{ width: "140px" }} alt="logo" />
              {/* Reference for textShadow: https://www.w3schools.com/cssref/css3_pr_text-shadow.php */}
              <div style={{ backgroundColor: '#4FE5F5'}}><br/><h1 style={{ color: '#1B0C7A', textShadow: '2px 5px 8px #c36ed6', align: 'center'}}>NumImajez</h1><br/></div>
            </div>  
            {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#f2cdda' }}>
              <p>We will have content coming soon!</p>
            </div> */}
          </div>
        {/* </div> */}
      </div> 

      {/* Third section of the Home page */}
      <div className="container mt-5 d-flex justify-content-center align-items-center">
        <div style={{ display: "flex", gap: "2px"}}>
          <div className="d-flex justify-content-center align-items-center" style={{ backgroundColor: '#BEC7EE', width: "700px", height: "600px"}}><br/>
              <div style={{ backgroundColor: '#DBEDED', width: "550px", height: "450px"}}><br/>
                {/* Reference used to create the shadow around the text: https://www.geeksforgeeks.org/css/css-font-border/ */}
                {/* Reference for textShadow: https://www.w3schools.com/cssref/css3_pr_text-shadow.php */}
                <h3 style={{ color: '#3f0264', textShadow: '2px 2px 6px #7c6fc4'}}>Make you selections for the game!<br/><br /></h3>                
                <p style={{ color: '#000000', fontSize: "20px", fontWeight: 700 }}><br/>Level<br/></p>
                {/* For the dropdown menu, here is the reference I used: https://www.geeksforgeeks.org/reactjs/react-bootstrap-dropdowns-menu-dividers/ */}
                  {/* Dropdown, additional reference: https://www.w3schools.com/bootstrap/bootstrap_dropdowns.asp */}
                  {/* Reference for select: https://react.dev/reference/react-dom/components/select */}
                  {/* These "options" can be used as a parameter later to pass to the system to actually add the correct type of service to the database, under that user's name. */}
                  {/* Reference for the select option: https://www.w3schools.com/tags/tag_select.asp */}
                  <div className="d-flex justify-content-center align-items-center" style={{ display: "flex", gap: "20px" }}>
                    <select id="level" style={{ textAlign: 'left', width: '300px' }} value={level} onChange={(e) => setLevel(e.target.value)}>
                      <option value="">Select</option>
                      <option value="easy">EASY</option>
                      <option value="medium">MEDIUM</option>
                      <option value="hard">HARD</option>
                    </select>
                  </div>
                <p style={{ color: '#000000', fontSize: "20px", fontWeight: 700 }}><br/>Contrast<br/></p>
                <div className="d-flex justify-content-center align-items-center" style={{ display: "flex", gap: "20px" }}>
                    <select id="contrast" style={{ textAlign: 'left', width: '300px' }} value={contrast} onChange={(e) => setContrast(e.target.value)}>
                      <option value="">Select</option>
                      <option value="highContrast">HIGH</option>
                      <option value="lowContrast">LOW</option>
                    </select>
                  </div>
                <p style={{ color: '#000000', fontSize: "20px", fontWeight: 700 }}><br/>Category<br/></p>
                <div className="d-flex justify-content-center align-items-center" style={{ display: "flex", gap: "20px" }}>
                    <select style={{ textAlign: 'left', width: '300px' }} value={category} onChange={(e) => setCategory(e.target.value)}>
                      <option value="">Select</option>
                      <option value="animals">ANIMALS</option>
                      <option value="boats">BOATS</option>
                    </select>
                  </div>


                  {/* Grab all the selections to pass to the userSelection variable. This will be passed to the GameStartPage for processing. */}
                  {/* Reference: https://devgex.com/en/article/00008850?utm_source=copilot.com */}
                  {/* <script>
                    const selectLevel = document.getElementById('level');
                    const selectContrast = document.getElementById('contrast');
                    const selectCategory = document.getElementById('category');
                    {/* Pass these selections to the userSelection variable */}
                    {/* userSelection = (level: selectedLevel, contrast: selectContrast, category: selectCategory);
                  </script> */}


                {/* Reference used to redirect to another page: https://www.geeksforgeeks.org/reactjs/how-to-redirect-to-another-page-in-reactjs/ */}
                {/* Add the submit button here, that will redirect to the FinalPgAppointment page, (using React Link to route to the page). */}
                {/* Reference used when redirecting to another page using the submit button: https://www.geeksforgeeks.org/reactjs/how-to-redirect-to-another-page-in-reactjs/ */}
                {/* Additional reference for re-routing to another page: https://reactrouter.com/en/main/hooks/use-navigate */}
                {/* Reference for passing parameters (level, contrast, animals): https://reactnavigation.org/docs/params/ */}
                {/* Pass the parameters using the variable "userSelection", which should have all the values stored from the user's selection made in the drop down menus */}
                {/* I used Copilot to figure out how to pass the parameters for "userSelection"! */}
                <br/><button className="btn btn-primary" onClick={() => {const userSelection = { level, contrast, category }; navigate('/memory-game/start', { replace: true, state: userSelection });}}>Submit</button>
              </div>
          </div>
        </div>
      </div>

      {/* Third section of the Home page, the footer */}
      <div className="container mt-5">
        <div className="mb-5">
            <div>
              {/* See if you can adjust the width to fit the screen */}
              <div style={{ backgroundColor: '#6FD5F4', width: "950px"}}><br/>
                <p style={{ color: '#000000', fontSize: "20px", fontWeight: 700 }}>Designed by: Krystan Kornafel, a third year Software Engineering student.<br/><br /></p>
              </div>
            </div>  
          </div>
      </div>

    </div>

  );
}


function MemoryGame() {
  return (
    <>
      <Outlet />
    </>
  );
}

export default MemoryGame;

export {GameHome, GameStartPage, DecisionPage, ResultsPage};
