//import React from 'react';
//import { Link, Outlet } from 'react-router-dom';
//Put a route to the services page
import './About.css'
import { Link } from 'react-router-dom';


//======================== About Page ====================================================================================
// Name: Krystan Kornafel
// Assignment: SEG3125 Assignment 2
// Description: This page provides the user with a bit of a background into the owner of the company. Additionally, the user
// is also provided with a link to the list of services and contact details for the company. 


function About() {
  return (
     //Reference used for background colour: https://www.w3schools.com/cssref/pr_background-color.php
    <div style={{ backgroundColor: '#c473ca' }}>
      {/* First section of the About page */}
      <div className="container mt-5">
        <div className="mb-5">
          {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#c473ca', border: '10px solid #215689' }}> */}
            <div>
              {/* Image generated by Copilot */}
              <img src="/Logo.png" className="float-start me-3 rounded" style={{ width: "175px" }} alt="logo" />
              <div style={{ backgroundColor: '#4FE5F5'}}><br/><h1>Chique Hairstylez</h1><br/></div>
            </div>  
            {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#f2cdda' }}>
              <p>We will have content coming soon!</p>
            </div> */}
          </div>
        {/* </div> */}
      </div> 

      {/* Second section of the About page */}
       {/* Reference for center alignment: https://mdbootstrap.com/docs/react/layout/vertical-alignment/ */}
      <div className="container mt-5 d-flex justify-content-center align-items-center">
        <div className="mb-5">
          <div style={{ display: "flex", alignItems: "center", gap: "2px" }}>
            {/* Image generated by Copilot */}
            <img src="/Main_Pg_Backgrnd.png" className="float-left ms-3 rounded" style={{ width: "300px" }} alt="logo" />
            <div style={{ backgroundColor: '#4FE5F5', width: "600px", height: "300px"}}><br/>
              {/* Reference for styling: https://www.pluralsight.com/resources/blog/guides/react-inline-styling */}
              <p style={{ color: '#8F0CB0', fontSize: "20px", fontWeight: 700 }}><br/>Chique Hairstylez is a family owned hair salon. Their Specialties include unique retro hairstyles, hair colouring, trims, and so much more! As a mother of 2, Brittany Jacobs wanted to provide her clients with unique, low-maintenance hairstyles such as perms, colouring, and trims. Check out the Services page for more details.</p><br/>
            </div>
          </div>
        </div>
      </div>

      {/* Third section of the About page */}
      <div className="container mt-5 d-flex justify-content-center align-items-center">
        <div style={{ display: "flex", gap: "2px"}}>
          <div>
            {/* Image generated by Copilot */}
            <Link to="/hairdresser/ServicesPage"><img src="/Services2_Img.png" className="float-left ms-3 rounded" style={{ width: "300px", height:"300px" }} alt="logo" /></Link>
            {/* <img src="/Services2_Img.png" className="float-left ms-3 rounded" style={{ width: "300px", height:"300px" }} alt="logo" /> */}
          </div>
          <div style={{ backgroundColor: '#4FE5F5', width: "400px", height: "300px"}}><br/>
              <p style={{ color: '#8F0CB0', fontSize: "20px", fontWeight: 700}}><br/>Contact Us<br/><br/>(613)-890-1234<br/>ChiqueHairstylez@gmail.com<br/><br/></p>
          </div>
        </div>
      </div>

      {/* Third section of the page: the footer */}
      <div className="container mt-5">
        <div className="mb-5">
            <div>
              <div style={{ backgroundColor: '#F46FF0'}}><br/>
                <p style={{ color: '#000000', fontSize: "20px", fontWeight: 700 }}><br/>Designed by: Krystan Kornafel, a third year Software Engineering student.<br/></p>
                <p style={{ color: '#690AE4', fontSize: "20px", fontWeight: 700 }}><br/>(613)-890-1234, ChiqueHairstylez@gmail.com<br/></p><br/><br/>
              </div>
            </div>  
          </div>
      </div>

    </div>
  );
}

export default About;
