import './FinalPgAppointment.css'
//For the navbar. For some reason, it stopped displaying the Navbar when you hit submit on the ApplyNow form.
//I am pretty sure the issue is in the way I routed these final pages in App.jsx
//They were called outside of the Hairdresser route, but right now, I can't get the path working inside it.
//This is my temporary fix for now so that the user can still access all the required pages.
import { Link, Outlet } from 'react-router-dom';

//======================== Final Page for the Appointment Booking ====================================================================================
// Name: Krystan Kornafel
// Assignment: SEG3125 Assignment 2
// Description: This React UI will be used to inform the user that their appointment request has been received successfully, and 
//that someone will contact them shortly. Once the user submits their request on the Book Appointment page (BookAppointment.jsx), 
//they are redirected to this page, which just acts as a way to acknowledge the user's request.



function AppointmentNavbar() {
  return (
    //Reference used for this: https://www.sitepoint.com/creating-a-navbar-in-react/
    //<nav className="navbar navbar-expand-lg navbar-dark bg-dark px-4">
    // <div className="navbar-center">
    <div className="container-fluid"style={{ backgroundColor: "#F46FF0", border: "1px solid #334155" }}> 
      <div className="navbar">
        {/* Reference used for spacing (aka "me-3, me-auto"): https://mdbootstrap.com/docs/react/utilities/spacing/ */}
        <ul className="navbar-nav me-auto mb-2 mb-lg-0 d-flex flex-row">
        {/* <div className="container-fluid"> */}
          {/* <span className="navbar-brand">Assign2</span> */}
          {/* <div className="navbar-nav"> */}
          {/* Add a link to the main UI page for the Portfolio */}
            <li className="nav-item me-3"><Link className="nav-link" to="/hairdresser">Home</Link></li>
            {/* <Link className="nav-link text-white" to="/about">About</Link> */}
            <li className="nav-item me-3"><Link className="nav-link" to="/hairdresser/about">About Us</Link></li>
            <li className="nav-item me-3"><Link className="nav-link" to="/hairdresser/applyNow">We are Hiring!</Link></li>
            <li className="nav-item me-3"><Link className="nav-link" to="/hairdresser/bookAppointment">Book Appointment</Link></li>
            <li className="nav-item"><Link className="nav-link" to="/hairdresser/contactUs">Contact Us</Link></li>
          {/* </div> */}
        {/* </div> */}
        </ul>
      </div>
    </div>
  );
}


function FinalPgAppointment() {
  return (
    <>
      <AppointmentNavbar />
      <Outlet />

      <div style={{ backgroundColor: '#c473ca' }}>
        {/* First section of the ApplyNow page */}
        <div className="container mt-5">
          <div className="mb-5">
            {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#c473ca', border: '10px solid #215689' }}> */}
              <div>
                {/* Image created by Copilot */}
                <img src="/Logo.png" className="float-start me-3 rounded" style={{ width: "175px" }} alt="logo" />
                <div style={{ backgroundColor: '#4FE5F5'}}><br/><h1>Chique Hairstylez</h1><br/></div>
              </div>  
              {/* <div className="border rounded p-3 mb-4" style={{ backgroundColor: '#f2cdda' }}>
                <p>We will have content coming soon!</p>
              </div> */}
            </div>
          {/* </div> */}
        </div> 

        {/* Process: Create textboxes with their corresponding box to RECEIVE text from user. Then create a submit button that redirects to the FinalPgApply Page */}

        {/* Modify to create the form */}
        <div className="container mt-5">
          <div className="mb-5 d-flex justify-content-center align-items-center">
            <div style={{ display: "flex", alignItems: "center", gap: "2px" }}>
              {/* Image generated by Gemini */}
              <img src="/Receptionist.png" className="float-start me-3 rounded" style={{ width: "700px" }} alt="logo" />
            </div>
          </div>
          <div className="mb-5 d-flex justify-content-center align-items-center" style={{ backgroundColor: '#5BE5CE', width: "700px", height: "300px", alignItems: "center"}}><br/>
                {/* Reference for styling: https://www.pluralsight.com/resources/blog/guides/react-inline-styling */}
                <p style={{ color: '#000000', fontSize: "20px", fontWeight: 700 }}><br/>Got your appointment! We'll call you soon!</p><br/>
            </div>
        </div>

        

        {/* Third section of the ApplyNow page, the footer */}
        <div className="container mt-5">
          <div className="mb-5">
              <div>
                <div style={{ backgroundColor: '#F46FF0'}}><br/>
                  <p style={{ color: '#000000', fontSize: "20px", fontWeight: 700 }}><br/>Designed by: Krystan Kornafel, a third year Software Engineering student.<br/></p>
                  <p style={{ color: '#690AE4', fontSize: "20px", fontWeight: 700 }}><br/>(613)-890-1234, ChiqueHairstylez@gmail.com<br/></p><br/><br/>
                </div>
              </div>  
            </div>
        </div>

      </div>

    </>

  );
}

export default FinalPgAppointment;
